


spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://8.131.242.140:7501/faster?characterEncoding=utf-8
        username: faster_dev
        password: faster_dev


    props:
      sql:
        show: true

com:
  github:
    misterchangray:
      financial:
        master: 127.0.0.1:7501
      redis:
        single:
          host: 8.131.242.140
          port: 7502
          password: t&23kfIuvde#.2
          db: 0


mybatis-plus:
  mapper-locations: classpath*:**/**/mapper/xml/*.xml

