
server:
  port: 7001

spring:
  application:
    name: financial

  profiles:
    active: dev


com:
  github:
    misterchangray:
      idservice:
        appId: 1
        appInstanceId: 1
logging:
  config: classpath:log4j2-spring.xml