


com:
  oss:
    aliyun:
      config:
        accessKeyId: 123123
        accessKeySecret: 33333
        roleArn: 4444444
        endpoint: ray.oss.aliyuncs.com
        regionId: cn-hangzhou
        bucketName: ttt
        defaultDir: /test/tmp

server:
  servlet:
    context-path: /fileupload
  port: 7501
